In [1]:
import numpy as np

In [2]:
a = np.array([23245, 27, 546, 215, -1234])

In [3]:
a

array([23245,    27,   546,   215, -1234])

In [4]:
l = [23245, 27, 546, 215]

In [6]:
l[1:]

[27, 546, 215]

In [7]:
l[0:2]

[23245, 27]

In [8]:
l[::2]

[23245, 546]

---

In [9]:
a

array([23245,    27,   546,   215, -1234])

In [10]:
a[2:]

array([  546,   215, -1234])

In [11]:
a[2:4]

array([546, 215])

In [12]:
b = a[2:4]
b

array([546, 215])

In [13]:
b[0]

np.int64(546)

In [15]:
b[:] = 111

In [16]:
b

array([111, 111])

In [17]:
a

array([23245,    27,   111,   111, -1234])

In [18]:
c = a.copy()

In [19]:
c

array([23245,    27,   111,   111, -1234])

In [20]:
a

array([23245,    27,   111,   111, -1234])