In [1]:
l = [23356, 27, 546, 215]

In [3]:
l[1:]

[27, 546, 215]

In [4]:
l[0]

23356

In [5]:
l[0:2]

[23356, 27]

In [7]:
l[::2]

[23356, 546]

---

In [8]:
import numpy as np

In [9]:
a = np.array([23245, 27, 546, 215, -1234])

In [10]:
a

array([23245,    27,   546,   215, -1234])

In [11]:
a[2:]

array([  546,   215, -1234])

In [12]:
a[2:4]

array([546, 215])

In [13]:
b = a[2:4]

In [14]:
b

array([546, 215])

In [15]:
b[0]

np.int64(546)

In [16]:
b[:]

array([546, 215])

In [17]:
b[:] = 111

In [18]:
b

array([111, 111])

In [19]:
a

array([23245,    27,   111,   111, -1234])

In [20]:
c = a.copy()

In [21]:
c

array([23245,    27,   111,   111, -1234])

In [22]:
c[0] = 0

In [23]:
c

array([    0,    27,   111,   111, -1234])

In [24]:
a

array([23245,    27,   111,   111, -1234])